name: Build TF650 App

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  android:
    name: Android APK
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.29.0

      - name: Generowanie struktury projektu
        run: |
          mkdir temp_proj
          cd temp_proj
          flutter create --platforms=android app
          cd ..
          cp -r temp_proj/app/android ./
          cp temp_proj/app/pubspec.yaml ./
          rm -rf temp_proj

      - name: Pobieranie pakietów
        run: flutter pub get

      - name: Budowanie APK
       run: flutter build apk --debug

      - name: Udostępnienie pliku APK
        uses: actions/upload-artifact@v4
        with:
          name: tf650-final-apk
          path: build/app/outputs/flutter-apk/app-debug.apk
